version: "3"
services:
  postgres:
    image: postgres:11
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - $PWD:/docker-entrypoint-initdb.d
