// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// ActorInfo represents a row from 'public.actor_info'.
type ActorInfo struct {
	ActorID   sql.NullInt64  `json:"actor_id"`   // actor_id
	FirstName sql.NullString `json:"first_name"` // first_name
	LastName  sql.NullString `json:"last_name"`  // last_name
	FilmInfo  sql.NullString `json:"film_info"`  // film_info
}
