// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"errors"
	"time"
)

// Country represents a row from 'public.country'.
type Country struct {
	CountryID  int       `json:"country_id"`  // country_id
	Country    string    `json:"country"`     // country
	LastUpdate time.Time `json:"last_update"` // last_update

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the Country exists in the database.
func (c *Country) Exists() bool {
	return c._exists
}

// Deleted provides information if the Country has been deleted from the database.
func (c *Country) Deleted() bool {
	return c._deleted
}

// Insert inserts the Country to the database.
func (c *Country) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if c._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key must be provided
	const sqlstr = `INSERT INTO public.country (` +
		`country_id, country, last_update` +
		`) VALUES (` +
		`$1, $2, $3` +
		`)`

	// run query
	XOLog(sqlstr, c.CountryID, c.Country, c.LastUpdate)
	err = db.QueryRow(sqlstr, c.CountryID, c.Country, c.LastUpdate).Scan(&c.CountryID)
	if err != nil {
		return err
	}

	// set existence
	c._exists = true

	return nil
}

// Update updates the Country in the database.
func (c *Country) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !c._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if c._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE public.country SET (` +
		`country, last_update` +
		`) = ( ` +
		`$1, $2` +
		`) WHERE country_id = $3`

	// run query
	XOLog(sqlstr, c.Country, c.LastUpdate, c.CountryID)
	_, err = db.Exec(sqlstr, c.Country, c.LastUpdate, c.CountryID)
	return err
}

// Save saves the Country to the database.
func (c *Country) Save(db XODB) error {
	if c.Exists() {
		return c.Update(db)
	}

	return c.Insert(db)
}

// Upsert performs an upsert for Country.
//
// NOTE: PostgreSQL 9.5+ only
func (c *Country) Upsert(db XODB) error {
	var err error

	// if already exist, bail
	if c._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO public.country (` +
		`country_id, country, last_update` +
		`) VALUES (` +
		`$1, $2, $3` +
		`) ON CONFLICT (country_id) DO UPDATE SET (` +
		`country_id, country, last_update` +
		`) = (` +
		`EXCLUDED.country_id, EXCLUDED.country, EXCLUDED.last_update` +
		`)`

	// run query
	XOLog(sqlstr, c.CountryID, c.Country, c.LastUpdate)
	_, err = db.Exec(sqlstr, c.CountryID, c.Country, c.LastUpdate)
	if err != nil {
		return err
	}

	// set existence
	c._exists = true

	return nil
}

// Delete deletes the Country from the database.
func (c *Country) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !c._exists {
		return nil
	}

	// if deleted, bail
	if c._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM public.country WHERE country_id = $1`

	// run query
	XOLog(sqlstr, c.CountryID)
	_, err = db.Exec(sqlstr, c.CountryID)
	if err != nil {
		return err
	}

	// set deleted
	c._deleted = true

	return nil
}

// CountryByCountryID retrieves a row from 'public.country' as a Country.
//
// Generated from index 'country_pkey'.
func CountryByCountryID(db XODB, countryID int) (*Country, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`country_id, country, last_update ` +
		`FROM public.country ` +
		`WHERE country_id = $1`

	// run query
	XOLog(sqlstr, countryID)
	c := Country{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, countryID).Scan(&c.CountryID, &c.Country, &c.LastUpdate)
	if err != nil {
		return nil, err
	}

	return &c, nil
}
