// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// FilmList represents a row from 'public.film_list'.
type FilmList struct {
	Fid         sql.NullInt64   `json:"fid"`         // fid
	Title       sql.NullString  `json:"title"`       // title
	Description sql.NullString  `json:"description"` // description
	Category    sql.NullString  `json:"category"`    // category
	Price       sql.NullFloat64 `json:"price"`       // price
	Length      sql.NullInt64   `json:"length"`      // length
	Rating      MpaaRating      `json:"rating"`      // rating
	Actors      sql.NullString  `json:"actors"`      // actors
}
