// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// SalesByStore represents a row from 'public.sales_by_store'.
type SalesByStore struct {
	Store      sql.NullString  `json:"store"`       // store
	Manager    sql.NullString  `json:"manager"`     // manager
	TotalSales sql.NullFloat64 `json:"total_sales"` // total_sales
}
