// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// SalesByFilmCategory represents a row from 'public.sales_by_film_category'.
type SalesByFilmCategory struct {
	Category   sql.NullString  `json:"category"`    // category
	TotalSales sql.NullFloat64 `json:"total_sales"` // total_sales
}
