// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// FilmInStock calls the stored procedure 'public.film_in_stock(integer, integer) SETOF integer' on db.
func FilmInStock(db XODB, v0 int, v1 int) ([]int, error) {
	var err error

	// sql query
	const sqlstr = `SELECT public.film_in_stock($1, $2)`

	// run query
	var ret []int
	XOLog(sqlstr, v0, v1)
	err = db.QueryRow(sqlstr, v0, v1).Scan(&ret)
	if err != nil {
		return nil, err
	}

	return ret, nil
}
