// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"time"
)

// GetCustomerBalance calls the stored procedure 'public.get_customer_balance(integer, timestamp without time zone) numeric' on db.
func GetCustomerBalance(db XODB, v0 int, v1 time.Time) (float64, error) {
	var err error

	// sql query
	const sqlstr = `SELECT public.get_customer_balance($1, $2)`

	// run query
	var ret float64
	XOLog(sqlstr, v0, v1)
	err = db.QueryRow(sqlstr, v0, v1).Scan(&ret)
	if err != nil {
		return 0.0, err
	}

	return ret, nil
}
