// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// InventoryHeldByCustomer calls the stored procedure 'public.inventory_held_by_customer(integer) integer' on db.
func InventoryHeldByCustomer(db XODB, v0 int) (int, error) {
	var err error

	// sql query
	const sqlstr = `SELECT public.inventory_held_by_customer($1)`

	// run query
	var ret int
	XOLog(sqlstr, v0)
	err = db.QueryRow(sqlstr, v0).Scan(&ret)
	if err != nil {
		return 0, err
	}

	return ret, nil
}
