// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"time"
)

// LastDay calls the stored procedure 'public.last_day(timestamp without time zone) date' on db.
func LastDay(db XODB, v0 time.Time) (time.Time, error) {
	var err error

	// sql query
	const sqlstr = `SELECT public.last_day($1)`

	// run query
	var ret time.Time
	XOLog(sqlstr, v0)
	err = db.QueryRow(sqlstr, v0).Scan(&ret)
	if err != nil {
		return time.Time{}, err
	}

	return ret, nil
}
