// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// RewardsReport calls the stored procedure 'public.rewards_report(integer, numeric) SETOF customer' on db.
func RewardsReport(db XODB, v0 int, v1 float64) ([]Customer, error) {
	var err error

	// sql query
	const sqlstr = `SELECT public.rewards_report($1, $2)`

	// run query
	var ret []Customer
	XOLog(sqlstr, v0, v1)
	err = db.QueryRow(sqlstr, v0, v1).Scan(&ret)
	if err != nil {
		return nil, err
	}

	return ret, nil
}
