// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// StaffList represents a row from 'public.staff_list'.
type StaffList struct {
	ID      sql.NullInt64  `json:"id"`       // id
	Name    sql.NullString `json:"name"`     // name
	Address sql.NullString `json:"address"`  // address
	ZipCode sql.NullString `json:"zip code"` // zip code
	Phone   sql.NullString `json:"phone"`    // phone
	City    sql.NullString `json:"city"`     // city
	Country sql.NullString `json:"country"`  // country
	Sid     sql.NullInt64  `json:"sid"`      // sid
}
